name: Deploy Backend to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/backend:latest -f backend/Dockerfile .
          docker push your-dockerhub-username/backend:latest

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v3
        with:
          manifests: |
            ./backend-deployment.yaml
          namespace: default
          images: |
            your-dockerhub-username/backend:latest
          kubectl-version: '1.21'
          cluster-name: ${{ secrets.K8S_CLUSTER_NAME }}
          cluster-admin-username: ${{ secrets.K8S_ADMIN_USERNAME }}
          cluster-admin-password: ${{ secrets.K8S_ADMIN_PASSWORD }}
